[package]
name = "include_aoc"
version = "0.1.0"
edition = "2021"
authors = ["Jeremy Haak <jeremyrhaak@gmail.com>"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
dotenv = "0.15.0"
fs2 = "0.4.3"
reqwest = { version = "0.11.22", features = ["blocking"] }
scratch = "1.0.7"
syn = "2.0.39"
